zcash/lcwg

meeting-notes/lcwg-dev-12.md
please review if I'm missing anything
=> Meeting 12 notes

README.md, meeting-notes/lcwg-dev-10.md, meeting-notes/lcwg-dev-13.md, meeting-notes/lcwg-dev-14.md, meeting-notes/lcwg-dev-15.md, meeting-notes/lcwg-dev-16.md, meeting-notes/lcwg-dev-17.md, meeting-notes/lcwg-dev-18.md
=> Add notes for LCWG 18

meeting-notes/lcwg-dev-19.md
@nighthawk24 I created this branch with a place holder for the notes you took for two meetings back.
:)
=> Draft notes for meeting 19

README.md, meeting-notes/lcwg-dev-48.md, meeting-notes/lcwg-dev-49.md, meeting-notes/lcwg-dev-50.md, meeting-notes/lcwg-dev-51.md, meeting-notes/lcwg-dev-52.md, meeting-notes/lcwg-dev-53.md, meeting-notes/lcwg-dev-54.md, meeting-notes/lcwg-dev-55.md, meeting-notes/lcwg-dev-56.md, meeting-notes/lcwg-dev-57.md, meeting-notes/lcwg-dev-58.md, meeting-notes/lcwg-dev-59.md
=> Lcwg 59th call, Aug 31st notes

README.md, meeting-notes/lcwg-dev-48.md, meeting-notes/lcwg-dev-49.md, meeting-notes/lcwg-dev-50.md, meeting-notes/lcwg-dev-51.md, meeting-notes/lcwg-dev-52.md, meeting-notes/lcwg-dev-53.md, meeting-notes/lcwg-dev-54.md
Notes for the past couple LCWG calls.
=> LCWG 49, 50, 51, 52, 53, 54

README.md, meeting-notes/lcwg-dev-48.md, meeting-notes/lcwg-dev-49.md, meeting-notes/lcwg-dev-50.md, meeting-notes/lcwg-dev-51.md, meeting-notes/lcwg-dev-52.md, meeting-notes/lcwg-dev-53.md, meeting-notes/lcwg-dev-54.md, meeting-notes/lcwg-dev-55.md, meeting-notes/lcwg-dev-56.md
This builds atop #53 
Closes #54
=> Lcwg 56 Aug 10th 2023

README.md, meeting-notes/lcwg-dev-48.md, meeting-notes/lcwg-dev-49.md, meeting-notes/lcwg-dev-50.md, meeting-notes/lcwg-dev-51.md, meeting-notes/lcwg-dev-52.md, meeting-notes/lcwg-dev-53.md, meeting-notes/lcwg-dev-54.md, meeting-notes/lcwg-dev-55.md, meeting-notes/lcwg-dev-56.md, meeting-notes/lcwg-dev-57.md, meeting-notes/lcwg-dev-58.md
[#58] Notes for LCWG Call 58 - Aug 24th 2023
closes #58
=> Notes for LCWG Call 58 - Aug 24th 2023

README.md, meeting-notes/lcwg-dev-60.md, meeting-notes/lcwg-dev-62.md
[#64] LCWG Call #62 Oct 5th
Closes #64
=>  LCWG Call #62 Oct 5th

README.md
=> [#66] fix wrong reference to google doc. Update "Who Manages..." section

README.md, meeting-notes/lcwg-dev-63.md
=> [#68] LCWG Call #63 Oct 19th

README.md, meeting-notes/lcwg-dev-64.md
=> LCWG #64 - Nov 2nd 2023

README.md, meeting-notes/lcwg-dev-65.md
=> LCWG #65 Meeting notes 

README.md, meeting-notes/lcwg-dev-66.md
=> Notes for LCWG Call #66 - Nov 30th

README.md, meeting-notes/lcwg-dev-67.md
=> [#76] LCWG call #67 notes

meeting-notes/lcwg-dev-69.md
=> [#78] Call #69 notes

meeting-notes/lcwg-dev-70.md
=> [#82] LCWG call notes #70

README.md, meeting-notes/lcwg-dev-70.md, meeting-notes/lcwg-dev-71.md
=> [#84] LCWG call #71 notes

README.md, meeting-notes/lcwg-dev-72.md
=> [#86] LCWG #72 call notes

README.md, meeting-notes/lcwg-dev-73.md
=> [#88] LCWG #73 call notes

README.md, meeting-notes/lcwg-dev-74.md
=> [#90] LCWG #74 call notes

README.md, meeting-notes/lcwg-dev-76.md, meeting-notes/lcwg-dev-77.md
=> Call notes for LCWG 76 and 77

meeting-notes/lcwg-dev-78.md
=> Notes for LCWG #78

README.md, meeting-notes/lcwg-dev-79.md
=> [#97] LCWG #79 call notes

meeting-notes/lcwg-dev-80.md
=> LCWG #80 call notes

README.md, meeting-notes/lcwg-dev-81.md
=> Call Notes LCWG #81

README.md, meeting-notes/lcwg-dev-82.md, meeting-notes/lcwg-dev-83.md
LCWG 82 call notes
closes #103
LCWG 83 call notes
closes #104
=> Lcwg #82 and  #83

README.md, meeting-notes/lcwg-dev-84.md
closes #106
Credits to @decentralistdan
=> [#106] LCWG #84 call notes

README.md, meeting-notes/lcwg-dev-86.md
=> [#109] LCWG #86 call notes

README.md, meeting-notes/lcwg-dev-87.md
=> [#111] LCWG #87 call notes

README.md, meeting-notes/lcwg-dev-88.md
=> [#113] LCWG #88 call notes

README.md, meeting-notes/lcwg-dev-89.md
=> [#115] LCWG #89 call notes

README.md, meeting-notes/lcwg-dev-91.md, meeting-notes/lcwg-dev-92.md
=> LCWG call notes for calls #91 and #92

README.md, meeting-notes/lcwg-dev-93.md
also removes the recording session since we've never used it and apparently won't
closes #122
=> [#122] LCWG #93 call notes

README.md, meeting-notes/lcwg-dev-94.md
=> [#125] LCWG Call #94 notes + fix on README

README.md, meeting-notes/lcwg-dev-95.md, meeting-notes/lcwg-dev-96.md
=> Lcwg 95 96

README.md, meeting-notes/lcwg-dev-101.md
=> [#138] LCWG #101 call notes

README.md, meeting-notes/lcwg-dev-102.md
=> [#140] LCWG #102 call notes
